--- #YAML:1.0
name:               CMS-Joomla
version:            0.02
abstract:           Joomla! CMS configuration and database access Perl module
author:
    - EPIPE Communications <epipe at cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBI:       0
    IO::File:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
